### PR TITLE
Add translation for reason

### PR DESCRIPTION
**Pull request by oshriromatrix**
In my feature i add, translation for reason and reason detail attribute

### CODE REVIEW

**Comment by dsevillamartin** [comment]
The translating should be done in the frontend, not the bAckend, when displaying the r reason. If we translate it in the bAckend, checking for a reason type won't work in other languages.

**Comment by oshriromatrix** [comment]
@datitisev 


> The translating should be done in the frontend, not the bAckend, when displaying the r reason. If we translate it in the bAckend, checking for a reason type won't work in other languages.

1) in frontend it is not possible to do the translate only in the backend.
2) i am check if the key is exist in current lang list at line 76 - 78 and in the line 91-93.
if translate not found it give the original text from data base.

This solution are copy from Flarum dev team.
see the file 
src/vendor/flarum/core/src/Api/Serializer/GroupSerializer.php at line 64 -73.
 same solution like what i am doing

**Comment by dsevillamartin** [comment]
Hm... Not sure why you say you can't translate in the frontend, but I see what you mean with the group serializer. The thing is, the group translations are just for the default groups (Admins, Members, Mods). You can check for those with the ID, but you can't check for reason type with ID.

I think this should still be done in the frontend, maybe wait for some other input though.

**Comment by oshriromatrix** [comment]
@datitisev 
> Hm... Not sure why you say you can't translate in the frontend, but I see what you mean with the group serializer. The thing is, the group translations are just for the default groups (Admins, Members, Mods). You can check for those with the ID, but you can't check for reason type with ID.
> 
> I think this should still be done in the frontend, maybe wait for some other input though.

i have id, the text in the data base is my id.
See how they compose the translation(in red is the id text from database)


image

image

**Review by askvortsov1 — CHANGES_REQUESTED** [review]
I would also prefer that the actual translation be done in the frontend. As far as I understand, the 2 functions for translating could just as easily be done in javascript, no?

**Review by franzliedke — CHANGES_REQUESTED** [review]
I also agree the translation should happen in the frontend.

Also, as far as I can tell, there is no reason to translate the "details", that's user provided text.

Might need to consider the changes from #18 for this.

**Comment by askvortsov1** [comment]
Closing as inactive, and https://github.com/flarum/flags/pull/30 seems to have superceded this.

**Pull request closed without merging**
