### PR TITLE
Add missing translation for the reason flag

### LINKED ISSUE #2331: [Flags] Should use proper translations
**Current Behavior**

**Expected Behavior**

Should return the translated string.

**Possible Solution**

By changing [addFlagsToPosts.js#L107](https://github.com/flarum/flags/blob/2cc558c9143702dbd17a164646d419a778c0831c/js/src/forum/addFlagsToPosts.js#L107)

```js
const reason = flag.reason();
```

to

```js
const reason = flag.reason() ? app.translator.trans(`flarum-flags.forum.flag_post.reason_${flag.reason()}_label`) : null;
```

**Additional Context**

Discuss: [https://discuss.flarum.org/d/25020](https://discuss.flarum.org/d/25020-flarum-flags-translations)

### PR DESCRIPTION
**Pull request by doceazedo**
Fixes flarum/core#2331

### CODE REVIEW

**Review by askvortsov1 — APPROVED** [review]
Makes sense to me, thanks!

**Comment by luceos** [comment]
Shouldn't this need a companion PR to English?

**Review by luceos — APPROVED** [review]

**Review by tankerkiller125 — APPROVED** [review]

**Review by clarkwinkelmann — CHANGES_REQUESTED** [review]
I see two people already approved, but as I said in the discussion I would have preferred a solution where we switched the `flarum-flags.forum.post.flagged_by_with_reason_text` translation with another one and remove the `{reason}` substitution altogether.

This solution might not play well with some languages where the order of words might need to change or the word termination be replaced in the main text depending on the reason.

Or alternatively to use this solution, I think we should wrap the reason around quotes or `em` tag to indicate it has been inserted into a standard phrase.

**Comment by askvortsov1** [comment]
On second thought, I think I prefer Clark's proposal as well (adding new translations for these)

**Comment by Nearata** [comment]
With something like this

```yml
flagged_by_as_inappropriate: "Flagged by {username} as Inappropriate"
...
```

you would no longer need `flagged_by_with_reason_text` anymore and neither `{reason}` but keep the constant to check the translation key.

In the frontend would be like

```js
const reason = flag.reason();
...
app.translator.trans(reason ? `flarum-flags.forum.post.flagged_by_as_${reason}` : 'flarum-flags.forum.post.flagged_by_text', {time, user})
```

**Comment by luceos** [comment]
Having a feeling there is some confusion here. @clarkwinkelmann @askvortsov1 just to confirm what @Nearata perhaps is trying to say. The PR here offers the ability to mutate the translation key `core.forum.some_reason` by making that key dynamic `core.forum.some_reason_because_$var` nothing else.. The variable is not inserted inside the text itself, but in the key that is retrieved.

**Comment by askvortsov1** [comment]
Yes, but that now-dynamic translation, which is stored in `const reason`, is then inserted as a variable into another translation (https://github.com/flarum/flags/pull/30/files#diff-4d059299f405f79cd188361bc0b159dfL112). That's what this PR is currently doing. What I believe @Nearata and @clarkwinkelmann are proposing (which I agree with) is creating new translations for text with reason, so that we're not inserting the result of one translation into another.

**Comment by luceos** [comment]
@askvortsov1 ah thanks for clarifying. I'm with you all on this 👍 Using translations inside translations isn't the way to go, unless we have no other way of solving it.

**Comment by clarkwinkelmann** [comment]
Has anyone tested how this looks with Akismet/Approval? Both of them create flags with different `type` attributes. Not sure whether this PR has any influence on those or not.

**Comment by Nearata** [comment]
@clarkwinkelmann Tested with no problems. Both extensions create their own `div.Post-flagged-flag`.

**Comment by askvortsov1** [comment]
> Has anyone tested how this looks with Akismet/Approval? Both of them create flags with different `type` attributes. Not sure whether this PR has any influence on those or not.

Would the above proposal with translation-per-flag type work though?

**Comment by clarkwinkelmann** [comment]
I have since taken a look at the implementation. There's in fact two attributes. `type` and `reason`. Reason is used for flags created through the Flags extension by users, which have the type `user`.

Other `type` of flags are created by extensions and those extensions customize how they look by extending `CommentPost.prototype.flagReason`. For example https://github.com/flarum/akismet/blob/master/js/src/forum/index.js#L18

So I don't think we need to care about the extensibility regarding `reason`. We just need to make sure the code doesn't crash catastrophically if `reason` is null, and I believe the code already takes care of that.

**Review by askvortsov1 — APPROVED** [review]
Tested locally, works well. Thank you!

**Pull request merged**
