### PR TITLE
Extract translation from FlagList.js

### PR DESCRIPTION
**Pull request by dcsjapan**
- Extracts one translation used in Flags dropdown.
- Changes in English language pack to follow.
- Please check syntax before merging!

Resolves: flarum/core#931

### CODE REVIEW

**Comment by tobyzerner** [comment]
So close! Syntax should be:

``` js
                        {app.translator.trans('flarum-flags.forum.flagged_posts.item_text', {username: username(post.user()), em: <em/>, post: post.discussion().title()})}
```

(only one set of curly braces)

**Comment by tobyzerner** [comment]
Also should the `post` argument be named `discussion`? `{username} in <em>{discussion}</em>`

**Comment by franzliedke** [comment]
I also [took care](https://github.com/flarum/flarum-ext-flags/commit/7a33b22fa93b1ea8780474e393b0bf8bb977a6bd) of this one.

Thanks again, @dcsjapan !

**Comment by dcsjapan** [comment]
@tobscure @franzliedke Thanks for the corrections! I had a feeling I'd got the brackets wrong.

**Pull request closed without merging**
